#!/bin/bash

NUC_WMI_CLI_VERSION="$(dpkg-query --show --showformat '${VERSION}\n' python3-nuc-wmi 2>/dev/null)"

function regression_test()
{
  set -x

  lsb_release -a
  uname -a

  time nuc_wmi-query_leds --debug 'NUC_10'
  time nuc_wmi-query_led_color_type --debug 'NUC_10' 'Power Button LED'
  time nuc_wmi-query_led_color_type --debug 'NUC_10' 'HDD LED'
  time nuc_wmi-query_led_color_type --debug 'NUC_10' 'RGB Header'
  time nuc_wmi-query_led_indicator_options --debug 'NUC_10' 'Power Button LED'
  time nuc_wmi-query_led_indicator_options --debug 'NUC_10' 'HDD LED'
  time nuc_wmi-query_led_indicator_options --debug 'NUC_10' 'RGB Header'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'Power Button LED' 'Power State Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'Power Button LED' 'Software Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'HDD LED' 'Software Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'RGB Header' 'Power State Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator'
  time nuc_wmi-query_led_control_items --debug 'NUC_10' 'RGB Header' 'Software Indicator'
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'Power Button LED' 'Power State Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'Power Button LED'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Behavior' Solid
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Frequency' '1.0Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Color' Blue
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Behavior' Strobing
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Frequency' '0.1Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Color' Amber
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Power State Indicator' 'S0 Indicator Brightness' 100
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'Power Button LED'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Color' Blue
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Behavior' 'Normally OFF, ON when active'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Behavior' 'Normally ON, OFF when active'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Color' Amber
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'Power Button LED' 'Software Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'Power Button LED'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Behavior' Solid
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Frequency' '1.0Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Color' Blue
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Behavior' Strobing
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Frequency' '0.1Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Color' Amber
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'Power Button LED' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'HDD LED'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color' Blue
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Behavior' 'Normally OFF, ON when active'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Behavior' 'Normally ON, OFF when active'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color' White
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color' Yellow
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'HDD LED' 'Software Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'HDD LED'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Behavior' Solid
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Frequency' '1.0Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color' Blue
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Behavior' Strobing
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Frequency' '0.1Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color' White
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color' Yellow
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'HDD LED' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'RGB Header' 'Power State Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'RGB Header'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Behavior' Solid
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Frequency' '1.0Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color' Blue
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Behavior' Strobing
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Frequency' '0.1Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color' White
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color' Green
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Power State Indicator' 'S0 Indicator Color'
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'RGB Header'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color' Blue
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Behavior' 'Normally OFF, ON when active'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Behavior' 'Normally ON, OFF when active'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color' White
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color' Yellow
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'HDD Activity Indicator' 'Color'
  time nuc_wmi-set_led_indicator_option --debug 'NUC_10' 'RGB Header' 'Software Indicator'
  time nuc_wmi-get_led_indicator_option --debug 'NUC_10' 'RGB Header'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Behavior' Solid
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Frequency' '1.0Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color' Blue
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Brightness'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Brightness' 0
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Behavior' Strobing
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Frequency' '0.1Hz'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color' White
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Behavior'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Blinking Frequency'
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color'
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Brightness' 100
  time nuc_wmi-set_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color' Yellow
  time nuc_wmi-get_led_control_item --debug 'NUC_10' 'RGB Header' 'Software Indicator' 'Color'
  time nuc_wmi-save_led_config --debug 'NUC_10'
  time nuc_wmi-switch_led_type --debug 'NUC_10' 'Single color LED'
  time nuc_wmi-switch_led_type --debug 'NUC_10' 'Multi color LED'
  time nuc_wmi-wmi_interface_spec_compliance_version --debug 'NUC_10'

  set +x
}

{ time regression_test; } > "nuc_10_cli_${NUC_WMI_CLI_VERSION}.log" 2>&1
